os: linux
dist: bionic
language: scala
branches:
  only:
    - master
scala:
  - 2.11.12
jdk:
  - openjdk8
before_cache:
  - find $HOME/.sbt -name "*.lock" -print -delete
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libuv1-dev
script:
  - sbt +compile +test
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.cache/coursier
