addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.5.3")
addSbtPlugin("com.eed3si9n"     % "sbt-dirty-money"  % "0.2.0")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"          % "2.0.1")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"     % "3.9.4")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"     % "2.3.4")
